apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sandbox
spec:
  project: testing
  source:
    repoURL: https://github.com/paramathmuni-sumanth/nginx-sandbox.git
    path: .
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: nginx-sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: sumanth-sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true