apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-celigo
  namespace: argocd
  labels:
    poc: kubearmor-prestop
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paramathmuni-sumanth/nginx-sandbox.git
    path: .
    targetRevision: kubearmor-prestop-poc
    helm:
      releaseName: nginx-celigo
      valueFiles:
        - values.yaml
        - poc/values-celigo-exec.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
